spring:
  datasource:
    db1:
      jdbc-url: jdbc:p6spy:mysql://192.168.5.232:3306/ptx_wms_system_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: cc
      password: patozon&123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
